# start index with one
set -g base-index 1
setw -g pane-base-index 1

# split window prefix change
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# keybind too reload source file
bind r source-file ~/.tmux.conf

# style
set -g status-style "bg=cyan fg=black"
